
int C1 = 13;
int C2 = 12;
int C3 = 11;
int C4 = 10;
int C5 = 9;
int C6 = 8;
int C7 = 7;
int C8 = 6;
int C9 = 5;
int C10 = 4;
int C11 = 3;
int C12 = 2;
int C13 = 1;
int C14 = 0;
int C15 = 14;
int C16 = 15;
int L1 = A0;
int L2 = A1;
int L3 = A2;
int L4 = A3;
int timer = 100;


void setup() {
  pinMode(C1, OUTPUT);
  pinMode(C2, OUTPUT);
  pinMode(C3, OUTPUT);
  pinMode(C4, OUTPUT);
  pinMode(C5, OUTPUT);
  pinMode(C6, OUTPUT);
  pinMode(C7, OUTPUT);
  pinMode(C8, OUTPUT);
  pinMode(C9, OUTPUT);
  pinMode(C10, OUTPUT);
  pinMode(C11, OUTPUT);
  pinMode(C12, OUTPUT);
  pinMode(C13, OUTPUT);
  pinMode(C14, OUTPUT);
  pinMode(C15, OUTPUT);
  pinMode(C16, OUTPUT);
  pinMode(L1, OUTPUT);
  pinMode(L2, OUTPUT);
  pinMode(L3, OUTPUT);
  pinMode(L4, OUTPUT);
  digitalWrite(L1, LOW);
  digitalWrite(L2, LOW);
  digitalWrite(L3, LOW);
  digitalWrite(L4, LOW);
  
}

void loop() {
   
  digitalWrite(C1, HIGH); 
  digitalWrite(C2, HIGH); 
  digitalWrite(C3, HIGH); 
  digitalWrite(C4, HIGH); 
  delay (timer); 
  digitalWrite(C1, HIGH); 
  digitalWrite(C2, HIGH); 
  digitalWrite(C7, HIGH); 
  digitalWrite(C8, HIGH); 
  digitalWrite(C3, LOW); 
  digitalWrite(C4, LOW); 
  delay (timer); 
  digitalWrite(C1, HIGH); 
  digitalWrite(C6, HIGH); 
  digitalWrite(C11, HIGH); 
  digitalWrite(C16, HIGH); 
  digitalWrite(C2, LOW);
  digitalWrite(C7, LOW);
  digitalWrite(C8, LOW);
  delay (timer); 
  digitalWrite(C1, HIGH); 
  digitalWrite(C5, HIGH); 
  digitalWrite(C10, HIGH); 
  digitalWrite(C14, HIGH); 
  digitalWrite(C6, LOW); 
  digitalWrite(C11, LOW); 
  digitalWrite(C16, LOW); 
  delay (timer);
  digitalWrite(C10, LOW); 
  digitalWrite(C14, LOW); 
  digitalWrite(C1, HIGH); 
  digitalWrite(C5, HIGH); 
  digitalWrite(C9, HIGH); 
  digitalWrite(C13, HIGH); 
  delay (timer); 
  digitalWrite(C1, LOW); 
  digitalWrite(C5, LOW);
  digitalWrite(C2, HIGH); 
  digitalWrite(C6, HIGH); 
  delay (timer); 
  digitalWrite(C2, LOW); 
  digitalWrite(C6, LOW); 
  digitalWrite(C9, LOW); 
  digitalWrite(C10, HIGH); 
  digitalWrite(C7, HIGH); 
  digitalWrite(C4, HIGH); 
  delay (timer); 
  digitalWrite(C10, LOW); 
  digitalWrite(C7, LOW); 
  digitalWrite(C4, LOW); 
  digitalWrite(C11, HIGH); 
  digitalWrite(C12, HIGH); 
  digitalWrite(C14, HIGH); 
  delay (timer); 
  digitalWrite(C11, LOW); 
  digitalWrite(C12, LOW); 
  digitalWrite(C14, HIGH);
  digitalWrite(C15, HIGH);
  digitalWrite(C16, HIGH);
  delay (timer); 
  digitalWrite(C13, LOW); 
  digitalWrite(C14, LOW); 
  digitalWrite(C9, HIGH);
  digitalWrite(C10, HIGH);    
  delay (timer); 
  digitalWrite(C9, LOW);
  digitalWrite(C10, LOW); 
  digitalWrite(C15, LOW);
  digitalWrite(C11, HIGH);  
  digitalWrite(C6, HIGH);  
  digitalWrite(C1, HIGH);
  delay (timer); 
  digitalWrite(C6, LOW);  
  digitalWrite(C1, LOW); 
  digitalWrite(C11, LOW);  
  digitalWrite(C12, HIGH);  
  digitalWrite(C7, HIGH);  
  digitalWrite(C3, HIGH);  
  delay (timer); 
  digitalWrite(C7, LOW);  
  digitalWrite(C3, LOW);      
  digitalWrite(C4, HIGH);  
  digitalWrite(C8, HIGH);    
  delay (timer);   
  digitalWrite(C12, LOW);  
  digitalWrite(C16, LOW);     
  digitalWrite(C11, HIGH);   
  digitalWrite(C15, HIGH);   
  delay (timer);    
  digitalWrite(C11, LOW);   
  digitalWrite(C15, LOW);   
  digitalWrite(C8, LOW);   
  digitalWrite(C7, HIGH);   
  digitalWrite(C10, HIGH);    
  digitalWrite(C13, HIGH);  
  delay (timer);  
  digitalWrite(C7, LOW);   
  digitalWrite(C10, LOW);    
  digitalWrite(C13, LOW);  
  digitalWrite(C3, HIGH); 
  digitalWrite(C5, HIGH); 
  digitalWrite(C6, HIGH); 
  delay (timer);  
  digitalWrite(C5, LOW); 
  digitalWrite(C6, LOW); 
}
  
